module.exports = {
    SYNC_CHAIN_VERSION: 'SYNC_CHAIN_VERSION',
    SYNC_CHAIN_VERSION_RESPONSE: 'SYNC_CHAIN_VERSION_RESPONSE',

    SYNC_CHAIN: 'SYNC_CHAIN',
    SYNC_CHAIN_RESPONSE: 'SYNC_CHAIN_RESPONSE',

    BROADCAST_NEW_BLOCK: 'BROADCAST_NEW_BLOCK',
    RECV_NEW_BLOCK: 'RECV_NEW_BLOCK'
};