version: '3.7'
services:
  node-1:
    container_name: node-1
    image: fragchain:latest
    entrypoint: "./vault/entrypoint.sh"
    networks:
      vault:
        ipv4_address: 172.16.0.10
    ports:
      - "4000"
      - "4444"
    volumes:
      - ~/github/vault:/vault

  node-2:
    container_name: node-2
    image: fragchain:latest
    entrypoint: "./vault/entrypoint.sh"
    networks:
      vault:
        ipv4_address: 172.16.0.20
    ports:
      - "4000"
      - "4444"
    volumes:
      - ~/github/vault:/vault

  node-3:
    container_name: node-3
    image: fragchain:latest
    entrypoint: "./vault/entrypoint.sh"
    networks:
      vault:
        ipv4_address: 172.16.0.30
    ports:
      - "4000"
      - "4444"
    volumes:
      - ~/github/vault:/vault

  node-4:
    container_name: node-4
    image: fragchain:latest
    entrypoint: "./vault/entrypoint.sh"
    networks:
      vault:
        ipv4_address: 172.16.0.40
    ports:
      - "4000"
      - "4444"
    volumes:
      - ~/github/vault:/vault

networks:
  vault:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"